version: "3.8"

services:
    db:
        image: postgres:17
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: desafio
        ports:
            - "5432:5432"
        volumes:
          - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql // Cria uma nova tabela no banco de dados